package planning

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sebihoermann/devdb-go/internal/storage"
)

const (
	ScaffoldAcceptanceImplement = "Implementation shipped: code lands, tests pass, acceptance closed in devdb."
	ScaffoldAcceptanceDesign    = "Define scope and acceptance criteria for this milestone before implementation."
)

// StructuredItemInput creates a plan item under a milestone with phase/step labels.
type StructuredItemInput struct {
	PlanID      string
	MilestoneID string
	Title       string
	Body        string
	SourceDoc   string
	ModelID     string
}

// AddStructuredItem inserts a structured plan item linked to a milestone.
func AddStructuredItem(db *sql.DB, in StructuredItemInput) (string, error) {
	var msNum int
	if err := db.QueryRow(`SELECT number FROM milestones WHERE id=?`, in.MilestoneID).Scan(&msNum); err != nil {
		return "", err
	}
	itemNum, err := nextItemNumber(db, in.PlanID, in.MilestoneID)
	if err != nil {
		return "", err
	}
	id, err := storage.NewID()
	if err != nil {
		return "", err
	}
	now := storage.NowUTC()
	phase := fmt.Sprintf("M%d", msNum)
	step := strconvItoa(itemNum)
	_, err = db.Exec(`
		INSERT INTO plan_items(id, plan_id, milestone_id, item_number, phase, step, title, body,
			source_doc, status, created_at, model_id)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'planned', ?, ?)`,
		id, in.PlanID, in.MilestoneID, itemNum, phase, step,
		in.Title, nullStr(in.Body), nullStr(in.SourceDoc), now, in.ModelID,
	)
	return id, err
}

func strconvItoa(n int) string {
	return fmt.Sprintf("%d", n)
}

// ScaffoldPlanInput configures plan scaffolding.
type ScaffoldPlanInput struct {
	Title          string
	Slug           string
	Body           string
	Mode           string
	MilestoneCount int
	OutputPath     string
	RepoRoot       string
	SkipAcceptance bool
	ModelID        string
}

// ScaffoldPlanResult summarizes a scaffold run.
type ScaffoldPlanResult struct {
	PlanID     string `json:"plan_id"`
	Slug       string `json:"slug"`
	Artifact   string `json:"artifact"`
	Milestones int    `json:"milestones"`
}

// ScaffoldPlan creates a plan skeleton and optional HTML artifact.
func ScaffoldPlan(db *sql.DB, in ScaffoldPlanInput) (ScaffoldPlanResult, error) {
	mode := strings.ToLower(strings.TrimSpace(in.Mode))
	if mode == "" {
		mode = "implement"
	}
	if mode != "implement" && mode != "design" {
		return ScaffoldPlanResult{}, fmt.Errorf("mode must be implement or design")
	}
	count := in.MilestoneCount
	if count <= 0 {
		count = 4
	}
	slug := in.Slug
	if slug == "" {
		slug = slugify(in.Title)
		if len(slug) > 40 {
			slug = slug[:40]
		}
	}
	body := in.Body
	if body == "" {
		body = fmt.Sprintf("Implementation plan scaffold for %s", in.Title)
	}

	planID, err := CreatePlan(db, CreatePlanInput{Slug: slug, Title: in.Title, Body: body, ModelID: in.ModelID})
	if err != nil {
		if strings.Contains(err.Error(), "UNIQUE constraint failed") {
			return ScaffoldPlanResult{}, fmt.Errorf("plan slug already exists: %s", slug)
		}
		return ScaffoldPlanResult{}, err
	}

	output := in.OutputPath
	if output == "" {
		output = filepath.Join("docs", slug+"-implementation-plan.html")
	}
	absOutput := output
	if !filepath.IsAbs(absOutput) {
		absOutput = filepath.Join(in.RepoRoot, output)
	}
	relArtifact := output
	if rel, err := filepath.Rel(in.RepoRoot, absOutput); err == nil {
		relArtifact = rel
	}

	itemVerb := "Implement"
	acceptance := ScaffoldAcceptanceImplement
	successHTML := scaffoldSuccessImplement()
	if mode == "design" {
		itemVerb = "Design"
		acceptance = ScaffoldAcceptanceDesign
		successHTML = scaffoldSuccessDesign()
	}

	var milestoneLines []string
	for n := 1; n <= count; n++ {
		title := fmt.Sprintf("M%d. Milestone %d", n, n)
		milestoneLines = append(milestoneLines, fmt.Sprintf("    <li>%s</li>", title))
		msID, err := AddMilestone(db, planID, title, fmt.Sprintf("Work track %d for %s", n, in.Title), in.ModelID, n)
		if err != nil {
			return ScaffoldPlanResult{}, err
		}
		itemID, err := AddStructuredItem(db, StructuredItemInput{
			PlanID: planID, MilestoneID: msID,
			Title: fmt.Sprintf("%s %s", itemVerb, title),
			Body:  fmt.Sprintf("Cover milestone %d. Link artifact: %s", n, relArtifact),
			SourceDoc: relArtifact, ModelID: in.ModelID,
		})
		if err != nil {
			return ScaffoldPlanResult{}, err
		}
		if !in.SkipAcceptance {
			if _, err := AddAcceptance(db, itemID, acceptance, in.ModelID, 1); err != nil {
				return ScaffoldPlanResult{}, err
			}
		}
	}

	if err := os.MkdirAll(filepath.Dir(absOutput), 0o755); err != nil {
		return ScaffoldPlanResult{}, err
	}
	desc := in.Body
	if desc == "" {
		desc = "Planning artifact generated by devdb plan scaffold."
	}
	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>%s</title>
</head>
<body>
  <h1>%s</h1>
  <p>%s</p>
  <h2>Milestones</h2>
  <ul>
%s
  </ul>
%s
</body>
</html>
`, in.Title, in.Title, desc, strings.Join(milestoneLines, "\n"), successHTML)
	if err := os.WriteFile(absOutput, []byte(html), 0o644); err != nil {
		return ScaffoldPlanResult{}, err
	}

	return ScaffoldPlanResult{
		PlanID: planID, Slug: slug, Artifact: relArtifact, Milestones: count,
	}, nil
}

func scaffoldSuccessImplement() string {
	return `  <h2>Success Criteria</h2>
  <ul>
    <li>Each milestone plan item ships working implementation (not design-only).</li>
    <li>Record passing verification with <code>devdb verify record</code>.</li>
    <li>Close acceptance with <code>devdb plan acceptance meet</code> then <code>devdb plan item close</code>.</li>
  </ul>`
}

func scaffoldSuccessDesign() string {
	return `  <h2>Success Criteria</h2>
  <ul>
    <li>Define scope and acceptance criteria per milestone before implementation.</li>
    <li>Promote with <code>devdb plan promote</code> when ready to implement.</li>
  </ul>`
}

// PromoteResult reports design-to-implement promotion counts.
type PromoteResult struct {
	PlanID            string `json:"id"`
	PlanRef           string `json:"plan"`
	TitlesUpdated     int    `json:"titles_updated"`
	AcceptanceUpdated int    `json:"acceptance_updated"`
}

// PromotePlan rewrites design-scaffolded titles and open acceptance text to implement mode.
func PromotePlan(db *sql.DB, planRef, modelID string) (PromoteResult, error) {
	planID, err := ResolvePlanID(db, planRef)
	if err != nil {
		return PromoteResult{}, err
	}
	rows, err := db.Query(`SELECT id, title FROM plan_items WHERE plan_id=? ORDER BY created_at`, planID)
	if err != nil {
		return PromoteResult{}, err
	}
	type itemRow struct {
		id, title string
	}
	var items []itemRow
	for rows.Next() {
		var itemID, title string
		if err := rows.Scan(&itemID, &title); err != nil {
			rows.Close()
			return PromoteResult{}, err
		}
		items = append(items, itemRow{id: itemID, title: title})
	}
	if err := rows.Close(); err != nil {
		return PromoteResult{}, err
	}
	if err := rows.Err(); err != nil {
		return PromoteResult{}, err
	}

	now := storage.NowUTC()
	var titlesUpdated, acceptanceUpdated int
	for _, item := range items {
		if strings.HasPrefix(item.title, "Design ") {
			if _, err := db.Exec(`UPDATE plan_items SET title=? WHERE id=?`, "Implement "+item.title[7:], item.id); err != nil {
				return PromoteResult{}, err
			}
			titlesUpdated++
		}
		accRows, err := db.Query(`
			SELECT id FROM plan_item_acceptance
			WHERE plan_item_id=? AND status='open' AND criterion=?`, item.id, ScaffoldAcceptanceDesign)
		if err != nil {
			return PromoteResult{}, err
		}
		var accIDs []string
		for accRows.Next() {
			var accID string
			if err := accRows.Scan(&accID); err != nil {
				accRows.Close()
				return PromoteResult{}, err
			}
			accIDs = append(accIDs, accID)
		}
		accRows.Close()
		for _, accID := range accIDs {
			if _, err := db.Exec(`
				UPDATE plan_item_acceptance SET criterion=?, updated_at=?, model_id=? WHERE id=?`,
				ScaffoldAcceptanceImplement, now, modelID, accID); err != nil {
				return PromoteResult{}, err
			}
			acceptanceUpdated++
		}
	}
	return PromoteResult{
		PlanID: planID, PlanRef: planRef,
		TitlesUpdated: titlesUpdated, AcceptanceUpdated: acceptanceUpdated,
	}, nil
}
